spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/career_canvas_db
    username: postgres
    password: 12345
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        default_schema: public